import{S as L,i as c,a as S}from"./assets/vendor-CRCB-GUD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const g of o.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&n(g)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();let f;function h(e){e.insertAdjacentHTML("afterbegin",'<span class="loader"></span>')}function d(){const e=document.querySelector(".loader");e&&e.remove()}function p(e){const t=document.querySelector(".gallery"),a=e.map(n=>`
      <a href="${n.largeImageURL}" class="gallery-link">
        <img class="img-gallery"
          src="${n.webformatURL}"
          alt="${n.tags}" 
          loading="lazy" />
        <ul class="list-wrapper">
          <li class="text-content"><b>Likes:</b> ${n.likes}</li>
          <li class="text-content"><b>Views:</b> ${n.views}</li>
          <li class="text-content"><b>Comments:</b> ${n.comments}</li>
          <li class="text-content"><b>Downloads:</b> ${n.downloads}</li>
        </ul>
      </a>
  `).join("");t.innerHTML=a,f?f.refresh():f=new L(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"})}function q(){const e=document.querySelector(".gallery a");if(e){const{height:t}=e.getBoundingClientRect(),a=document.querySelector(".list-wrapper"),{height:n}=a.getBoundingClientRect(),r=t+n;window.scrollBy({top:r*4,behavior:"smooth"})}}function $(){const e=document.querySelector(".gallery");e.innerHTML=""}function m(e){c.info({title:"Info",message:e,position:"topRight",backgroundColor:"red",messageColor:"white",titleColor:"white"})}const v="45922188-6c9bdbb7442dfc44aff321ea7",E="https://pixabay.com/api/";async function b(e,t=1,a=15){const n=new URLSearchParams({key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:a}),r=`${E}?${n.toString()}`;try{const o=await S.get(r);return console.log(o.data),o.data}catch(o){throw console.error("There was an error with the fetch operation:",o),o}}const H=document.querySelector(".search-form"),P=document.querySelector('[name="searchQuery"]'),w=document.querySelector(".gallery"),s=document.querySelector(".load-more");let u="",l=1,y=0,i=15;s.style.display="none";H.addEventListener("submit",async e=>{if(e.preventDefault(),u=P.value.trim(),!u){c.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}$(),s.style.display="none",h(w),l=1;try{const t=await b(u,l,i);if(d(),y=t.totalHits,!t||t.hits.length===0){m("Sorry, there are no images matching your search query. Please try again!");return}p(t.hits),t.hits.length>=i&&l*i<y&&(s.style.display="block")}catch(t){console.error("Error fetching images:",t),c.error({title:"Error",message:`Error: ${t.message}`,position:"topRight"})}finally{d()}});s.addEventListener("click",async()=>{if(l*i>=y){c.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."}),s.style.display="none";return}l+=1,h(w);try{const e=await b(u,l,i);if(d(),!e||e.hits.length===0){m("No more images found."),s.style.display="none";return}p(e.hits),q(),l*i<y?s.style.display="block":s.style.display="none"}catch(e){console.error("Error fetching images:",e),c.error({title:"Error",message:`Error: ${e.message}`,position:"topRight"})}finally{d()}});
//# sourceMappingURL=index.js.map
