import{S as w,i as c,a as S}from"./assets/vendor-CRCB-GUD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const f of o.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&s(f)}).observe(document,{childList:!0,subtree:!0});function i(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(r){if(r.ep)return;r.ep=!0;const o=i(r);fetch(r.href,o)}})();let p;function g(e){e.insertAdjacentHTML("afterbegin",'<span class="loader"></span>')}function d(){const e=document.querySelector(".loader");e&&e.remove()}function h(e){const t=document.querySelector(".gallery"),i=e.map(s=>`
      <a href="${s.largeImageURL}" class="gallery-link">
        <img class="img-gallery"
          src="${s.webformatURL}"
          alt="${s.tags}" 
          loading="lazy" />
        <ul class="list-wrapper">
          <li class="text-content"><b>Likes:</b> ${s.likes}</li>
          <li class="text-content"><b>Views:</b> ${s.views}</li>
          <li class="text-content"><b>Comments:</b> ${s.comments}</li>
          <li class="text-content"><b>Downloads:</b> ${s.downloads}</li>
        </ul>
      </a>
  `).join("");t.innerHTML=i,p?p.refresh():p=new w(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"})}function q(){const e=document.querySelector(".gallery");e.innerHTML=""}function m(e){c.info({title:"Info",message:e,position:"topRight",backgroundColor:"red",messageColor:"white",titleColor:"white"})}const $="45922188-6c9bdbb7442dfc44aff321ea7",E="https://pixabay.com/api/";async function b(e,t=1,i=15){const s=new URLSearchParams({key:$,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:i}),r=`${E}?${s.toString()}`;try{const o=await S.get(r);return console.log(o.data),o.data}catch(o){throw console.error("There was an error with the fetch operation:",o),o}}const P=document.querySelector(".search-form"),v=document.querySelector('[name="searchQuery"]'),L=document.querySelector(".gallery"),n=document.querySelector(".load-more");let u="",a=1,y=0,l=15;n.style.display="none";P.addEventListener("submit",async e=>{if(e.preventDefault(),u=v.value.trim(),!u){c.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}q(),n.style.display="none",g(L),a=1;try{const t=await b(u,a,l);if(d(),y=t.totalHits,!t||t.hits.length===0){m("Sorry, there are no images matching your search query. Please try again!");return}h(t.hits),t.hits.length>=l&&a*l<y&&(n.style.display="block")}catch(t){console.error("Error fetching images:",t),c.error({title:"Error",message:`Error: ${t.message}`,position:"topRight"})}finally{d()}});n.addEventListener("click",async()=>{if(a*l>=y){c.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."}),n.style.display="none";return}a+=1,g(L);try{const e=await b(u,a,l);if(d(),!e||e.hits.length===0){m("No more images found."),n.style.display="none";return}h(e.hits),a*l<y?n.style.display="block":n.style.display="none"}catch(e){console.error("Error fetching images:",e),c.error({title:"Error",message:`Error: ${e.message}`,position:"topRight"})}finally{d()}});
//# sourceMappingURL=index.js.map
